### ISSUE TITLE
Fail to install UC20 when TPM supports SM3_256

### ISSUE THREAD

**Issue by EthanHsieh** [canonical/go-tpm2#7]
Error message:
the-tool[336]: error: error locking access to sealed keys: cannot execute hash sequence: TPM returned an invalid response for command TPM_CC_EventSequenceComplete: cannot unmarshal response parameters: cannot unmarshal argument at index 0: cannot process list type tpm2.TaggedHashList: cannot process element at index 3 from list type tpm2.TaggedHashList: cannot process custom type tpm2.TaggedHash, inside container type tpm2.TaggedHashList: cannot determine digest size for unknown algorithm TPM_ALG_SM3_256

Based on the commit below, go-tpm2 doesn't support SM3_256 because the crypto package[1] doesn't support SM3_256 now.

commit bd7cad4936577a496ebfca7272fef34c32e3bc0b
Author: Chris Coulson <chris.coulson@canonical.com>
Date: Tue Aug 10 17:46:55 2021 +0100
    Use HashAlgorithmId instead of crypto.Hash in various places
    
BIOS and TPM2 hardware support four hash algorithms: SHA1, SHA3256, SHA384, and SM3_256.
Could go-tpm2 use other algorithms when it finds that the default one (SM3_256) is unsupported.

LP bug: #1938678

[1] https://cs.opensource.google/go/x/crypto

**Comment by chrisccoulson** [comment]
This is fixed already by https://github.com/canonical/go-tpm2/commit/96eb110220ece5922dc7b691422fff12735f1880

**Comment by EthanHsieh** [comment]
@chrisccoulson 
The latest secboot seems to call old function, Supported()[1].
So, It's failed to build snapd with latest go-tpm2 and secboot.
May I know when secboot will support new API?

[1] https://github.com/snapcore/secboot/blob/master/tpm2/keydata.go#L133

**Comment by anthonywong** [comment]
> @chrisccoulson
> The latest secboot seems to call old function, Supported()[1].
> So, It's failed to build snapd with latest go-tpm2 and secboot.
> May I know when secboot will support new API?

@chrisccoulson Do you prefer this issue be reported to secboot?

**Comment by EthanHsieh** [comment]
![error_message](https://user-images.githubusercontent.com/2486575/129667701-3a886cbd-1887-4b6a-a7f5-a8640e091164.jpg)

@chrisccoulson 
I backported 96eb110 to 32171bd[1], but it's still failed to install uc20 when SM3 256 hash algorithm is enabled.
Error messages:
the-tool[334]: panic: crypto: requested hash function #0 is unavailable.
[FAILED] Failed to start the-tool.service.
the-tool[334]: crypto.Hash.New(0x0, 0xc420310400, 0x0)
the-tool[334]:   /snap/go/3133/src/crypto/crypto.go:89 +0x110

Could you help to take a look at this issue?
For detailed log, please refer to the attached photo.

[1] https://github.com/EthanHsieh/go-tpm2/tree/test

**Comment by chrisccoulson** [comment]
> ![error_message](https://user-images.githubusercontent.com/2486575/129667701-3a886cbd-1887-4b6a-a7f5-a8640e091164.jpg)
> 
> @chrisccoulson
> I backported [96eb110](https://github.com/canonical/go-tpm2/commit/96eb110220ece5922dc7b691422fff12735f1880) to [32171bd](https://github.com/canonical/go-tpm2/commit/32171bd353b113ff4793dc3c65a019d749674bc6)[1], but it's still failed to install uc20 when SM3 256 hash algorithm is enabled.
> Error messages:
> the-tool[334]: panic: crypto: requested hash function #0 is unavailable.
> [FAILED] Failed to start the-tool.service.
> the-tool[334]: crypto.Hash.New(0x0, 0xc420310400, 0x0)
> the-tool[334]: /snap/go/3133/src/crypto/crypto.go:89 +0x110
> 
> Could you help to take a look at this issue?
> For detailed log, please refer to the attached photo.
> 
> [1] https://github.com/EthanHsieh/go-tpm2/tree/test

https://github.com/snapcore/secboot/pull/166 will probably fix that
